./find_streak_len.py --constellation_name onewb --datalocation simulation_dbs/satellite_sim_0.0_onew_v2.2_1yrs.db
./find_streak_len.py --constellation_name slv1 --datalocation simulation_dbs/satellite_sim_0.0_slv1_v2.2_1yrs.db
./find_streak_len.py --constellation_name slv2 --datalocation simulation_dbs/satellite_sim_0.0_slv2_v2.2_1yrs.db
./find_streak_len.py --constellation_name onewb --datalocation simulation_dbs/satellite_sim_0.1_onew_v2.2_1yrs.db
./find_streak_len.py --constellation_name slv1 --datalocation simulation_dbs/satellite_sim_0.1_slv1_v2.2_1yrs.db
./find_streak_len.py --constellation_name slv2 --datalocation simulation_dbs/satellite_sim_0.1_slv2_v2.2_1yrs.db
./find_streak_len.py --constellation_name onewb --datalocation simulation_dbs/satellite_sim_1.0_onew_v2.2_1yrs.db
./find_streak_len.py --constellation_name slv1 --datalocation simulation_dbs/satellite_sim_1.0_slv1_v2.2_1yrs.db
./find_streak_len.py --constellation_name slv2 --datalocation simulation_dbs/satellite_sim_1.0_slv2_v2.2_1yrs.db
./find_streak_len.py --constellation_name onewb --datalocation simulation_dbs/satellite_sim_10.0_onew_v2.2_1yrs.db
./find_streak_len.py --constellation_name slv1 --datalocation simulation_dbs/satellite_sim_10.0_slv1_v2.2_1yrs.db
./find_streak_len.py --constellation_name slv2 --datalocation simulation_dbs/satellite_sim_10.0_slv2_v2.2_1yrs.db
./find_streak_len.py --constellation_name onewb --datalocation simulation_dbs/satellite_sim_5.0_onew_v2.2_1yrs.db
./find_streak_len.py --constellation_name slv1 --datalocation simulation_dbs/satellite_sim_5.0_slv1_v2.2_1yrs.db
./find_streak_len.py --constellation_name slv2 --datalocation simulation_dbs/satellite_sim_5.0_slv2_v2.2_1yrs.db
./find_streak_len.py --constellation_name onewb --datalocation simulation_dbs/satellite_sim_500.0_onew_v2.2_1yrs.db
./find_streak_len.py --constellation_name slv1 --datalocation simulation_dbs/satellite_sim_500.0_slv1_v2.2_1yrs.db
./find_streak_len.py --constellation_name slv2 --datalocation simulation_dbs/satellite_sim_500.0_slv2_v2.2_1yrs.db
